PRAGMA foreign_keys = ON;

CREATE TABLE xh_cage_code (
	cagecdxh VARCHAR(5) NOT NULL, 
	canamexh VARCHAR(25), 
	castrexh VARCHAR(25), 
	cacityxh VARCHAR(20), 
	castatxh VARCHAR(2), 
	canatnxh VARCHAR(20), 
	capozoxh VARCHAR(10), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xh PRIMARY KEY (cagecdxh)
);

CREATE TABLE xa_end_item (
	eiacodxa VARCHAR(10) NOT NULL, 
	lcnstrxa VARCHAR(18), 
	addltmxa NUMERIC(2, 0), 
	ctdltmxa NUMERIC(3, 0), 
	contnoxa VARCHAR(19), 
	csreorxa NUMERIC(4, 2), 
	csprroxa NUMERIC(4, 2), 
	demilcxa NUMERIC(2, 0), 
	discntxa NUMERIC(3, 1), 
	essalvxa NUMERIC(2, 0), 
	hlcspcxa NUMERIC(2, 0), 
	intbinxa NUMERIC(4, 0), 
	incatcxa NUMERIC(4, 0), 
	intiutxa NUMERIC(3, 1), 
	invstgxa NUMERIC(4, 2), 
	lodfacxa NUMERIC(3, 2), 
	wsoplvxa NUMERIC(2, 0), 
	oprlifxa NUMERIC(2, 0), 
	prstovxa NUMERIC(2, 0), 
	prstomxa NUMERIC(2, 0), 
	profacxa NUMERIC(3, 2), 
	rcbincxa NUMERIC(4, 0), 
	rccatcxa NUMERIC(4, 0), 
	restcrxa NUMERIC(2, 0), 
	saflvlxa NUMERIC(2, 0), 
	secsfcxa NUMERIC(3, 2), 
	trncstxa NUMERIC(4, 2), 
	wstyaqxa CHAR(1), 
	tsscodxa CHAR(1), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xa PRIMARY KEY (eiacodxa)
);

CREATE TABLE xi_tech_manual_index (
	tmcodexi VARCHAR(3) NOT NULL, 
	tmnumbxi VARCHAR(30), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xi PRIMARY KEY (tmcodexi)
);

CREATE TABLE cj_job_duty_assignment (
	jobcodcj VARCHAR(2) NOT NULL, 
	dutycdcj VARCHAR(4) NOT NULL, 
	jobdescj VARCHAR(40), 
	dutiescj VARCHAR(240), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_cj PRIMARY KEY (jobcodcj, dutycdcj)
);

CREATE TABLE fa_facility (
	facnamfa VARCHAR(32) NOT NULL, 
	facccdfa VARCHAR(6) NOT NULL, 
	factypfa CHAR(1) NOT NULL, 
	facclafa VARCHAR(19), 
	drclasfa VARCHAR(3), 
	fadnumfa VARCHAR(32), 
	fadrevfa VARCHAR(2), 
	faareafa NUMERIC(6, 0), 
	faarumfa VARCHAR(2), 
	facncofa NUMERIC(10, 2), 
	conuomfa VARCHAR(2), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_fa PRIMARY KEY (facnamfa, facccdfa, factypfa)
);

CREATE TABLE fc_baseline_facility_narrative (
	facnamfc VARCHAR(32) NOT NULL, 
	facccdfc VARCHAR(6) NOT NULL, 
	factypfc CHAR(1) NOT NULL, 
	fbnacdfc CHAR(1) NOT NULL, 
	texseqfc NUMERIC(5, 0) NOT NULL, 
	fabnarfc TEXT, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_fc PRIMARY KEY (facnamfc, facccdfc, factypfc, fbnacdfc, texseqfc)
);

CREATE TABLE fd_new_facility_narrative (
	facnamfd VARCHAR(32) NOT NULL, 
	facccdfd VARCHAR(6) NOT NULL, 
	factypfd CHAR(1) NOT NULL, 
	nmfncdfd CHAR(1) NOT NULL, 
	texseqfd NUMERIC(5, 0) NOT NULL, 
	nmfnarfd TEXT, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_fd PRIMARY KEY (facnamfd, facccdfd, factypfd, nmfncdfd, texseqfd)
);

CREATE TABLE ga_skill_specialty (
	skspcdga VARCHAR(7) NOT NULL, 
	sklvcdga CHAR(1), 
	hrlartga NUMERIC(6, 2), 
	trncosga NUMERIC(9, 2), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ga PRIMARY KEY (skspcdga)
);

CREATE TABLE ha_item_identification (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	itnameha VARCHAR(19), 
	inamecha VARCHAR(5), 
	refnccha CHAR(1), 
	refnvcha NUMERIC(1, 0), 
	dlscrcha CHAR(1), 
	docidcha VARCHAR(3), 
	itmmgcha CHAR(1), 
	cognsnha VARCHAR(2), 
	smmnsnha VARCHAR(2), 
	matnsnha CHAR(1), 
	fscnsnha VARCHAR(4), 
	niinsnha VARCHAR(9), 
	actnsnha VARCHAR(2), 
	uiconvha NUMERIC(5, 0), 
	shlifeha VARCHAR(3), 
	slactnha VARCHAR(2), 
	ppslstha CHAR(1), 
	docavcha CHAR(1), 
	prdldtha NUMERIC(2, 0), 
	spmaccha CHAR(1), 
	smaincha CHAR(1), 
	critcdha CHAR(1), 
	pmicodha CHAR(1), 
	saipcdha CHAR(1), 
	aaplccha CHAR(1), 
	bbplccha CHAR(1), 
	ccplccha CHAR(1), 
	ddplccha CHAR(1), 
	eeplccha CHAR(1), 
	ffplccha CHAR(1), 
	ggplccha CHAR(1), 
	hhplccha CHAR(1), 
	jjplccha CHAR(1), 
	kkplccha CHAR(1), 
	llplccha CHAR(1), 
	mmplccha CHAR(1), 
	physecha CHAR(1), 
	adpeqpha NUMERIC(1, 0), 
	demiliha CHAR(1), 
	acqmetha NUMERIC(1, 0), 
	amsufcha CHAR(1), 
	hmscosha NUMERIC(8, 0), 
	hwdcosha NUMERIC(8, 0), 
	hwscosha NUMERIC(8, 0), 
	cticodha VARCHAR(2), 
	uweighha VARCHAR(5), 
	ulengtha NUMERIC(4, 1), 
	uwidthha NUMERIC(4, 1), 
	uheighha NUMERIC(4, 1), 
	hazcodha CHAR(1), 
	unitmsha VARCHAR(2), 
	unitisha VARCHAR(2), 
	linnumha VARCHAR(6), 
	crititha VARCHAR(13), 
	indmatha VARCHAR(19), 
	mtleadha NUMERIC(3, 0), 
	mtlwgtha NUMERIC(6, 3), 
	materlha VARCHAR(240), 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ha PRIMARY KEY (cagecdxh, refnumha), 
	CONSTRAINT fk_ha_xh FOREIGN KEY(cagecdxh) REFERENCES xh_cage_code (cagecdxh)
);

CREATE TABLE ea_support_equipment (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	flitnmea VARCHAR(42), 
	seiccdea VARCHAR(2), 
	aqdcofea VARCHAR(15), 
	endartea VARCHAR(26), 
	aidrqdea CHAR(1), 
	datfadea VARCHAR(6), 
	calintea NUMERIC(2, 0), 
	calitmea CHAR(1), 
	calrqdea CHAR(1), 
	calstdea CHAR(1), 
	caltimea NUMERIC(5, 0), 
	cmrsrcea CHAR(1), 
	cntrnoea VARCHAR(19), 
	cfegfeea CHAR(1), 
	custcdea CHAR(1), 
	drwclsea VARCHAR(3), 
	ecoanlea CHAR(1), 
	famgrpea VARCHAR(10), 
	genecdea VARCHAR(5), 
	govdesea VARCHAR(20), 
	hdwrprea NUMERIC(8, 0), 
	ilsprcea NUMERIC(8, 0), 
	dsnprcea NUMERIC(8, 0), 
	exunprea NUMERIC(8, 0), 
	pasthrea NUMERIC(8, 0), 
	oscostea NUMERIC(8, 0), 
	rcurcsea NUMERIC(8, 0), 
	licystea CHAR(1), 
	lifspnea NUMERIC(2, 0), 
	lgctcdea CHAR(1), 
	lgdcofea VARCHAR(15), 
	lsarcdea CHAR(1), 
	mgtplnea CHAR(1), 
	mgcoatea VARCHAR(10), 
	semtbfea NUMERIC(10, 0), 
	smtbmaea NUMERIC(10, 0), 
	semttrea NUMERIC(5, 2), 
	mobfacea CHAR(1), 
	modchgea CHAR(1), 
	oprhgtea NUMERIC(4, 1), 
	oplengea NUMERIC(4, 1), 
	opwidtea NUMERIC(4, 1), 
	oprwgtea NUMERIC(6, 1), 
	lwhoumea VARCHAR(2), 
	wgtoumea VARCHAR(2), 
	pcblvlea CHAR(1), 
	callvlea CHAR(1), 
	rprlvlea CHAR(1), 
	smrcseea VARCHAR(6), 
	tmrqcdea VARCHAR(17), 
	oprmanea VARCHAR(16), 
	sscoprea VARCHAR(7), 
	preatyea VARCHAR(25), 
	proeleea VARCHAR(3), 
	psicpoea VARCHAR(2), 
	sericcea NUMERIC(1, 0), 
	revassea VARCHAR(4), 
	slftstea CHAR(1), 
	sentraea CHAR(1), 
	serdesea CHAR(1), 
	useserea VARCHAR(8), 
	sketchea CHAR(1), 
	sprfacea VARCHAR(4), 
	spmgntea CHAR(1), 
	siascnea VARCHAR(7), 
	stohgtea NUMERIC(4, 1), 
	stolenea NUMERIC(4, 1), 
	stowdtea NUMERIC(4, 1), 
	stowgtea NUMERIC(6, 1), 
	lwhsumea VARCHAR(2), 
	wgtsumea VARCHAR(2), 
	seshphea NUMERIC(4, 1), 
	seshplea NUMERIC(4, 1), 
	seshpwea NUMERIC(4, 1), 
	seshwtea NUMERIC(6, 1), 
	umshipea VARCHAR(2), 
	umsewtea VARCHAR(2), 
	segrcdea NUMERIC(3, 0), 
	sereqdea CHAR(1), 
	tecevlea VARCHAR(3), 
	tstlngea VARCHAR(6), 
	tstptsea CHAR(1), 
	tmdercea CHAR(1), 
	tmderiea VARCHAR(7), 
	typclsea CHAR(1), 
	typeeqea VARCHAR(4), 
	yrfldgea NUMERIC(2, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ea PRIMARY KEY (cagecdxh, refnumha), 
	CONSTRAINT fk_ea_ha FOREIGN KEY(cagecdxh, refnumha) REFERENCES ha_item_identification (cagecdxh, refnumha)
);

CREATE TABLE xb_lcn_indentured_item (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	lcnindxb CHAR(1), 
	lcnamexb VARCHAR(19), 
	tmfgcdxb VARCHAR(11), 
	sysidnxb CHAR(1), 
	secitmxb CHAR(1), 
	ramindxb CHAR(1), 
	parent_lsacon VARCHAR(18), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xb PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb), 
	CONSTRAINT fk_xb_xa FOREIGN KEY(eiacodxa) REFERENCES xa_end_item (eiacodxa) ON DELETE CASCADE
);

CREATE TABLE hb_additional_reference (
	cagecdhb VARCHAR(5) NOT NULL, 
	refnumhb VARCHAR(32) NOT NULL, 
	adcagehb VARCHAR(5) NOT NULL, 
	addrefhb VARCHAR(32) NOT NULL, 
	adrncchb CHAR(1), 
	adrnvchb NUMERIC(1, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hb PRIMARY KEY (cagecdhb, refnumhb, adcagehb, addrefhb), 
	CONSTRAINT fk_hb_ha FOREIGN KEY(cagecdhb, refnumhb) REFERENCES ha_item_identification (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hc_ctic_cage (
	cagecdhc VARCHAR(5) NOT NULL, 
	refnumhc VARCHAR(32) NOT NULL, 
	ctcagehc VARCHAR(5) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hc PRIMARY KEY (cagecdhc, refnumhc, ctcagehc), 
	CONSTRAINT fk_hc_ha FOREIGN KEY(cagecdhc, refnumhc) REFERENCES ha_item_identification (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hd_unit_issue_price (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	uiprichd NUMERIC(10, 2) NOT NULL, 
	lotqfmhd NUMERIC(6, 0), 
	lotqtohd NUMERIC(6, 0), 
	curprchd CHAR(1), 
	tuiprchd CHAR(1), 
	prouiphd CHAR(1), 
	fiscyrhd VARCHAR(2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hd PRIMARY KEY (cagecdxh, refnumha, uiprichd), 
	CONSTRAINT fk_hd_ha FOREIGN KEY(cagecdxh, refnumha) REFERENCES ha_item_identification (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE he_unit_measure_price (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	umpriche NUMERIC(10, 2) NOT NULL, 
	lotqfmhe NUMERIC(6, 0), 
	lotqtohe NUMERIC(6, 0), 
	curprche CHAR(1), 
	tumprche CHAR(1), 
	proumphe CHAR(1), 
	fiscyrhe VARCHAR(2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_he PRIMARY KEY (cagecdxh, refnumha, umpriche), 
	CONSTRAINT fk_he_ha FOREIGN KEY(cagecdxh, refnumha) REFERENCES ha_item_identification (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hf_packaging_req (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	degprohf CHAR(1) NOT NULL, 
	uniconhf VARCHAR(2), 
	uclevlhf CHAR(1), 
	pkgcodhf VARCHAR(3), 
	paccathf VARCHAR(4), 
	mepreshf VARCHAR(2), 
	cdprochf VARCHAR(1), 
	prsmathf VARCHAR(2), 
	wrapmthf VARCHAR(2), 
	cushmahf VARCHAR(2), 
	custhihf CHAR(1), 
	qtyupkhf VARCHAR(3), 
	intconhf VARCHAR(2), 
	incqtyhf VARCHAR(3), 
	spemrkhf VARCHAR(2), 
	unpkwthf VARCHAR(5), 
	lenupkhf NUMERIC(4, 1), 
	widupkhf NUMERIC(4, 1), 
	depupkhf NUMERIC(4, 1), 
	unpkcuhf NUMERIC(7, 3), 
	optprihf CHAR(1), 
	spinumhf VARCHAR(10), 
	spirevhf CHAR(1), 
	spdatehf NUMERIC(5, 0), 
	connsnhf VARCHAR(20), 
	suppkdhf VARCHAR(59), 
	pkcagehf VARCHAR(5), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hf PRIMARY KEY (cagecdxh, refnumha, degprohf), 
	CONSTRAINT fk_hf_ha FOREIGN KEY(cagecdxh, refnumha) REFERENCES ha_item_identification (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hm_basis_of_issue (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	boictrhm NUMERIC(1, 0) NOT NULL, 
	qtyboihm NUMERIC(5, 0), 
	ratiobhm VARCHAR(8), 
	lvlboihm CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hm PRIMARY KEY (cagecdxh, refnumha, boictrhm), 
	CONSTRAINT fk_hm_ha FOREIGN KEY(cagecdxh, refnumha) REFERENCES ha_item_identification (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ce_task_remark (
	eiacodxa VARCHAR(10) NOT NULL, 
	tskrrcce VARCHAR(2) NOT NULL, 
	tskremce VARCHAR(240), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ce PRIMARY KEY (eiacodxa, tskrrcce), 
	CONSTRAINT fk_ce_xa FOREIGN KEY(eiacodxa) REFERENCES xa_end_item (eiacodxa)
);

CREATE TABLE uc_operational_test_program (
	otpcaguc VARCHAR(5) NOT NULL, 
	otprefuc VARCHAR(32) NOT NULL, 
	otpacruc NUMERIC(8, 0), 
	otpacnuc NUMERIC(8, 0), 
	otpctpuc CHAR(1), 
	otpsfcuc CHAR(1), 
	otpsrduc VARCHAR(10), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_uc PRIMARY KEY (otpcaguc, otprefuc), 
	CONSTRAINT fk_uc_ha FOREIGN KEY(otpcaguc, otprefuc) REFERENCES ha_item_identification (cagecdxh, refnumha)
);

CREATE TABLE ui_adapter_interconnector (
	aidcagui VARCHAR(5) NOT NULL, 
	aidrefui VARCHAR(32) NOT NULL, 
	aiducnui NUMERIC(8, 0), 
	aiducrui NUMERIC(8, 0), 
	aidsrdui VARCHAR(10), 
	aidcutui NUMERIC(2, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ui PRIMARY KEY (aidcagui, aidrefui), 
	CONSTRAINT fk_ui_ha FOREIGN KEY(aidcagui, aidrefui) REFERENCES ha_item_identification (cagecdxh, refnumha)
);

CREATE TABLE uk_ate_test_station (
	atecaguk VARCHAR(5) NOT NULL, 
	aterefuk VARCHAR(32) NOT NULL, 
	ategdsuk VARCHAR(20), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_uk PRIMARY KEY (atecaguk, aterefuk), 
	CONSTRAINT fk_uk_ha FOREIGN KEY(atecaguk, aterefuk) REFERENCES ha_item_identification (cagecdxh, refnumha)
);

CREATE TABLE bl_mission_phase_mode (
	eiacodxa VARCHAR(10) NOT NULL, 
	misspcbl VARCHAR(1) NOT NULL, 
	mpopldbl VARCHAR(65), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bl PRIMARY KEY (eiacodxa, misspcbl), 
	CONSTRAINT fk_bl_xa FOREIGN KEY(eiacodxa) REFERENCES xa_end_item (eiacodxa) ON DELETE CASCADE
);

CREATE TABLE fb_facility_narrative (
	facnamfa VARCHAR(32) NOT NULL, 
	facccdfa VARCHAR(6) NOT NULL, 
	factypfa CHAR(1) NOT NULL, 
	fncodefb CHAR(1) NOT NULL, 
	texseqfb NUMERIC(5, 0) NOT NULL, 
	facnarfb TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_fb PRIMARY KEY (facnamfa, facccdfa, factypfa, fncodefb, texseqfb), 
	CONSTRAINT fk_fb_fa FOREIGN KEY(facnamfa, facccdfa, factypfa) REFERENCES fa_facility (facnamfa, facccdfa, factypfa) ON DELETE CASCADE
);

CREATE TABLE gb_new_modified_skill (
	mdcsscgb VARCHAR(7) NOT NULL, 
	mdsclcgb CHAR(1), 
	skspcdga VARCHAR(7), 
	dprnrsgb VARCHAR(19), 
	rppcivgb VARCHAR(4), 
	rppmilgb VARCHAR(3), 
	scrsscgb NUMERIC(1, 0), 
	ssctesgb NUMERIC(3, 0), 
	abafqtgb NUMERIC(2, 0), 
	aaexrlgb NUMERIC(2, 0), 
	aaexrhgb NUMERIC(2, 0), 
	aalprlgb NUMERIC(2, 0), 
	aalprhgb NUMERIC(2, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_gb PRIMARY KEY (mdcsscgb), 
	CONSTRAINT fk_gb_ga FOREIGN KEY(skspcdga) REFERENCES ga_skill_specialty (skspcdga)
);

CREATE TABLE ai_modeling_data (
	eiacodxa VARCHAR(10) NOT NULL, 
	serdesai CHAR(1) NOT NULL, 
	omlvlcai CHAR(1) NOT NULL, 
	labratai NUMERIC(4, 2), 
	noshpsai NUMERIC(2, 0), 
	rpwscsai NUMERIC(4, 2), 
	rqdstkai NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ai PRIMARY KEY (eiacodxa, serdesai, omlvlcai), 
	CONSTRAINT fk_ai_xa FOREIGN KEY(eiacodxa) REFERENCES xa_end_item (eiacodxa) ON DELETE CASCADE
);

CREATE TABLE em_system_equipment (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	scagecem VARCHAR(5) NOT NULL, 
	srefnoem VARCHAR(32) NOT NULL, 
	qtytstem NUMERIC(3, 0), 
	gfaeidem VARCHAR(26), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_em PRIMARY KEY (cagecdxh, refnumha, scagecem, srefnoem), 
	CONSTRAINT fk_em_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE eb_allocation_data (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	aldcnmeb VARCHAR(10) NOT NULL, 
	alorg1eb NUMERIC(3, 0), 
	alorg2eb NUMERIC(3, 0), 
	alorg3eb NUMERIC(3, 0), 
	alorg4eb NUMERIC(3, 0), 
	alorg5eb NUMERIC(3, 0), 
	alorg6eb NUMERIC(3, 0), 
	alorg7eb NUMERIC(3, 0), 
	alorg8eb NUMERIC(3, 0), 
	alorg9eb NUMERIC(3, 0), 
	alrg10eb NUMERIC(3, 0), 
	aldndseb VARCHAR(9), 
	alexrneb VARCHAR(3), 
	allvcdeb CHAR(1), 
	almlvleb VARCHAR(2), 
	alstideb VARCHAR(5), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_eb PRIMARY KEY (cagecdxh, refnumha, aldcnmeb), 
	CONSTRAINT fk_eb_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ec_support_equip_parameters (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	pargpcec VARCHAR(2) NOT NULL, 
	calproec VARCHAR(20), 
	parparec VARCHAR(12), 
	rngfrmec NUMERIC(10, 0), 
	rngtocec NUMERIC(10, 0), 
	paraccec VARCHAR(26), 
	sparioec CHAR(1), 
	parrvcec CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ec PRIMARY KEY (cagecdxh, refnumha, pargpcec), 
	CONSTRAINT fk_ec_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ed_support_equip_authorization (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	actnamed VARCHAR(50) NOT NULL, 
	typacted VARCHAR(15), 
	numacted NUMERIC(3, 0), 
	seqtyaed NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ed PRIMARY KEY (cagecdxh, refnumha, actnamed), 
	CONSTRAINT fk_ed_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ef_serd_data (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	serdnoef VARCHAR(10) NOT NULL, 
	srdrevef VARCHAR(2) NOT NULL, 
	statusef CHAR(1), 
	intsubef VARCHAR(6), 
	dtgvdsef VARCHAR(6), 
	dtrvsbef VARCHAR(6), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ef PRIMARY KEY (cagecdxh, refnumha, serdnoef, srdrevef), 
	CONSTRAINT fk_ef_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ee_support_equip_narrative (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	senarcee CHAR(1) NOT NULL, 
	texseqee NUMERIC(5, 0) NOT NULL, 
	seqnaree TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ee PRIMARY KEY (cagecdxh, refnumha, senarcee, texseqee), 
	CONSTRAINT fk_ee_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ei_input_power_source (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	ipsopnei NUMERIC(2, 0) NOT NULL, 
	ipacdcei CHAR(1), 
	ipfrmxei NUMERIC(3, 0), 
	iprgmxei NUMERIC(3, 0), 
	ipsrgmei NUMERIC(3, 0), 
	ipoprgei NUMERIC(3, 0), 
	ipmxrpei NUMERIC(4, 2), 
	ipphasei NUMERIC(1, 0), 
	ippowrei NUMERIC(5, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ei PRIMARY KEY (cagecdxh, refnumha, ipsopnei), 
	CONSTRAINT fk_ei_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ej_support_equip_design_data (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	dsndatej CHAR(1) NOT NULL, 
	cntrecej CHAR(1), 
	estprcej NUMERIC(8, 0), 
	govrqdej CHAR(1), 
	ddccscej VARCHAR(40), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ej PRIMARY KEY (cagecdxh, refnumha, dsndatej), 
	CONSTRAINT fk_ej_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ek_supercedure_data (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	sprcagek VARCHAR(5) NOT NULL, 
	sprrefek VARCHAR(32) NOT NULL, 
	sutypeek CHAR(1) NOT NULL, 
	supitnek VARCHAR(19), 
	susrnoek VARCHAR(10), 
	reasupek VARCHAR(2), 
	iccodeek VARCHAR(2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ek PRIMARY KEY (cagecdxh, refnumha, sprcagek, sprrefek), 
	CONSTRAINT fk_ek_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE el_ils_requirement (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	irccodel CHAR(1) NOT NULL, 
	conrecel CHAR(1), 
	estprcel NUMERIC(8, 0), 
	govrqdel CHAR(1), 
	ircscoel VARCHAR(40), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_el PRIMARY KEY (cagecdxh, refnumha, irccodel), 
	CONSTRAINT fk_el_ea FOREIGN KEY(cagecdxh, refnumha) REFERENCES ea_support_equipment (cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE ua_unit_under_test (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	utalloua VARCHAR(10), 
	umntplua VARCHAR(23), 
	uttrdnua VARCHAR(15), 
	utwprfua VARCHAR(6), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ua PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua), 
	CONSTRAINT fk_ua_xb FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE xd_system_serial_number (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	frsnumxd VARCHAR(10) NOT NULL, 
	tosnumxd VARCHAR(10) NOT NULL, 
	snuuocxd VARCHAR(3) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xd PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, frsnumxd, tosnumxd), 
	CONSTRAINT fk_xd_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE xf_lcn_uoc_mapping (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxf VARCHAR(18) NOT NULL, 
	altlcnxf VARCHAR(2) NOT NULL, 
	lcntypxf CHAR(1) NOT NULL, 
	lcnseixf VARCHAR(18) NOT NULL, 
	alcseixf VARCHAR(2) NOT NULL, 
	ltyseixf CHAR(1) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xf PRIMARY KEY (eiacodxa, lsaconxf, altlcnxf, lcntypxf, lcnseixf, alcseixf, ltyseixf), 
	CONSTRAINT fk_xf_item FOREIGN KEY(eiacodxa, lsaconxf, altlcnxf, lcntypxf) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb), 
	CONSTRAINT fk_xf_system FOREIGN KEY(eiacodxa, lcnseixf, alcseixf, ltyseixf) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb)
);

CREATE TABLE xg_lcn_mapping (
	eiacodxa VARCHAR(10) NOT NULL, 
	plsacnxg VARCHAR(18) NOT NULL, 
	palcnczg VARCHAR(2) NOT NULL, 
	plcntyzg CHAR(1) NOT NULL, 
	flsacnxg VARCHAR(18) NOT NULL, 
	falcnczg VARCHAR(2) NOT NULL, 
	flcntyzg CHAR(1) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xg PRIMARY KEY (eiacodxa, plsacnxg, palcnczg, plcntyzg), 
	CONSTRAINT fk_xg_func FOREIGN KEY(eiacodxa, flsacnxg, falcnczg, flcntyzg) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb), 
	CONSTRAINT fk_xg_phy FOREIGN KEY(eiacodxa, plsacnxg, palcnczg, plcntyzg) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb)
);

CREATE TABLE xc_system_end_item (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	uocseixc VARCHAR(3) NOT NULL, 
	pccnumxc VARCHAR(6), 
	itmdesxc VARCHAR(26), 
	plisnoxc VARCHAR(5), 
	toccodxc CHAR(1), 
	qtyasyxc VARCHAR(4), 
	qtypeixc VARCHAR(5), 
	traseixc CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xc PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, uocseixc), 
	CONSTRAINT fk_xc_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE ca_task_requirement (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	refeiaca VARCHAR(10), 
	reflcnca VARCHAR(18), 
	refalcca VARCHAR(2), 
	reftypca CHAR(1), 
	reftskca VARCHAR(7), 
	aorlcnca VARCHAR(18), 
	aoralcca VARCHAR(2), 
	aortypca CHAR(1), 
	aormsbca CHAR(1), 
	taskidca VARCHAR(36), 
	tskfrqca NUMERIC(7, 4), 
	tskcrcca CHAR(1), 
	hrdcpcca CHAR(1), 
	hazmpcca CHAR(1), 
	pmcsidca CHAR(1), 
	msdmetca NUMERIC(5, 2), 
	prdmetca NUMERIC(5, 2), 
	msdmmhca NUMERIC(5, 2), 
	prdmmhca NUMERIC(5, 2), 
	pmdtecca CHAR(1), 
	smdtecca CHAR(1), 
	ftrnrqca CHAR(1), 
	trnrqcca CHAR(1), 
	trnrecca CHAR(1), 
	trnlocca VARCHAR(4), 
	trnratca VARCHAR(4), 
	tsereqca CHAR(1), 
	prstdaca CHAR(1), 
	prstdbca CHAR(1), 
	prstdcca CHAR(1), 
	tcondaca CHAR(1), 
	tcondbca CHAR(1), 
	tcondcca CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ca PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca), 
	CONSTRAINT fk_ca_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE hg_part_application (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	plisnohg VARCHAR(5), 
	qtyasyhg VARCHAR(4), 
	qtypeihg VARCHAR(5), 
	supindhg CHAR(1), 
	dataschg CHAR(1), 
	prosichg VARCHAR(3), 
	lliptdhg CHAR(1), 
	pplptdhg CHAR(1), 
	sfpptdhg CHAR(1), 
	cblptdhg CHAR(1), 
	rilptdhg CHAR(1), 
	islptdhg CHAR(1), 
	pclptdhg CHAR(1), 
	ttlptdhg CHAR(1), 
	scpptdhg CHAR(1), 
	araptdhg CHAR(1), 
	arbptdhg CHAR(1), 
	toccodhg CHAR(1), 
	indcodhg VARCHAR(1), 
	piplishg VARCHAR(5), 
	saplishg VARCHAR(5), 
	hardcihg CHAR(1), 
	remipihg CHAR(1), 
	lrunithg CHAR(1), 
	itmcathg VARCHAR(2), 
	esscodhg NUMERIC(1, 0), 
	smrcodhg VARCHAR(6), 
	mrronehg NUMERIC(8, 4), 
	mrrtwohg NUMERIC(8, 3), 
	mrrmodhg VARCHAR(7), 
	ortdoohg NUMERIC(3, 0), 
	frtdffhg NUMERIC(3, 0), 
	hrtdhhhg NUMERIC(3, 0), 
	lrtdllhg NUMERIC(3, 0), 
	drtdddhg NUMERIC(3, 0), 
	minreuhg NUMERIC(3, 0), 
	maotimhg VARCHAR(4), 
	maiacthg CHAR(1), 
	rissbuhg NUMERIC(3, 0), 
	rmsslihg NUMERIC(3, 0), 
	rtllqthg NUMERIC(3, 0), 
	totqtyhg NUMERIC(6, 0), 
	omtdoohg NUMERIC(2, 0), 
	fmtdffhg NUMERIC(2, 0), 
	hmtdhhhg NUMERIC(2, 0), 
	lmtdllhg NUMERIC(2, 0), 
	dmtdddhg NUMERIC(2, 0), 
	cbdmtdhg NUMERIC(2, 0), 
	cadmtdhg NUMERIC(2, 0), 
	orctoohg NUMERIC(3, 0), 
	frctffhg NUMERIC(3, 0), 
	hrcthhhg NUMERIC(3, 0), 
	lrctllhg NUMERIC(3, 0), 
	drctddhg NUMERIC(3, 0), 
	conrcthg NUMERIC(3, 0), 
	noretshg NUMERIC(3, 0), 
	repsurhg NUMERIC(3, 0), 
	drponehg VARCHAR(6), 
	drptwohg VARCHAR(6), 
	wrkucdhg VARCHAR(7), 
	allowchg VARCHAR(2), 
	aliqtyhg NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hg PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha), 
	CONSTRAINT fk_hg_ha FOREIGN KEY(cagecdxh, refnumha) REFERENCES ha_item_identification (cagecdxh, refnumha), 
	CONSTRAINT fk_hg_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb)
);

CREATE TABLE ue_test_program_instruction (
	otpcaguc VARCHAR(5) NOT NULL, 
	otprefuc VARCHAR(32) NOT NULL, 
	tpicague VARCHAR(5) NOT NULL, 
	tpirefue VARCHAR(32) NOT NULL, 
	tpaucrue NUMERIC(8, 0), 
	tpaucnue NUMERIC(8, 0), 
	tpistsue CHAR(1), 
	tpitdpue CHAR(1), 
	tpisrdue VARCHAR(10), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ue PRIMARY KEY (otpcaguc, otprefuc, tpicague, tpirefue), 
	CONSTRAINT fk_ue_uc FOREIGN KEY(otpcaguc, otprefuc) REFERENCES uc_operational_test_program (otpcaguc, otprefuc) ON DELETE CASCADE
);

CREATE TABLE um_se_item_uut (
	sutcagum VARCHAR(5) NOT NULL, 
	sutrefum VARCHAR(32) NOT NULL, 
	sutallum VARCHAR(10), 
	sutstcum CHAR(1), 
	mntplnum VARCHAR(23), 
	trdnumum VARCHAR(15), 
	wkpkrfum VARCHAR(6), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_um PRIMARY KEY (sutcagum, sutrefum), 
	CONSTRAINT fk_um_ea FOREIGN KEY(sutcagum, sutrefum) REFERENCES ea_support_equipment (cagecdxh, refnumha)
);

CREATE TABLE ba_ram_characteristics (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	meqlinba CHAR(1), 
	convfaba NUMERIC(5, 0), 
	fiambaba NUMERIC(2, 0), 
	fipfgaba NUMERIC(3, 1), 
	bdlpgaba NUMERIC(2, 0), 
	fiambbba NUMERIC(2, 0), 
	fipfgbba NUMERIC(3, 1), 
	bdlpgbba NUMERIC(2, 0), 
	bitndpba NUMERIC(2, 0), 
	bitropba NUMERIC(2, 0), 
	frdataba VARCHAR(32), 
	preovcba CHAR(1), 
	seccleba NUMERIC(1, 0), 
	supconba CHAR(1), 
	weouliba NUMERIC(6, 2), 
	wolimbba CHAR(1), 
	logstaba CHAR(1), 
	logaccba CHAR(1), 
	logmaiba CHAR(1), 
	logsafba CHAR(1), 
	logtepba CHAR(1), 
	logskiba CHAR(1), 
	logtrnba CHAR(1), 
	logconba CHAR(1), 
	logpatba CHAR(1), 
	logfloba CHAR(1), 
	loglabba CHAR(1), 
	logdspba CHAR(1), 
	logcrcba CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ba PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb), 
	CONSTRAINT fk_ba_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE bk_ram_criticality (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	misspcbl VARCHAR(1) NOT NULL, 
	fmshscbk CHAR(1) NOT NULL, 
	ricritbk NUMERIC(10, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bk PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, misspcbl, fmshscbk), 
	CONSTRAINT fk_bk_bl FOREIGN KEY(eiacodxa, misspcbl) REFERENCES bl_mission_phase_mode (eiacodxa, misspcbl), 
	CONSTRAINT fk_bk_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE gc_new_skill_narrative (
	mdcsscgb VARCHAR(7) NOT NULL, 
	nmsncdgc CHAR(1) NOT NULL, 
	texseqgc NUMERIC(5, 0) NOT NULL, 
	nmsnargc TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_gc PRIMARY KEY (mdcsscgb, nmsncdgc, texseqgc), 
	CONSTRAINT fk_gc_gb FOREIGN KEY(mdcsscgb) REFERENCES gb_new_modified_skill (mdcsscgb) ON DELETE CASCADE
);

CREATE TABLE gd_skill_aptitude (
	mdcsscgb VARCHAR(7) NOT NULL, 
	asvapegd VARCHAR(2) NOT NULL, 
	aaeerlgd NUMERIC(3, 0), 
	aaeerhgd NUMERIC(3, 0), 
	aaelplgd NUMERIC(3, 0), 
	aaelphgd NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_gd PRIMARY KEY (mdcsscgb, asvapegd), 
	CONSTRAINT fk_gd_gb FOREIGN KEY(mdcsscgb) REFERENCES gb_new_modified_skill (mdcsscgb) ON DELETE CASCADE
);

CREATE TABLE ja_transportation (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	trnindja CHAR(1), 
	sectidja NUMERIC(2, 0), 
	enhatcja CHAR(1), 
	delschja CHAR(1), 
	connumja VARCHAR(19), 
	propsnja VARCHAR(60), 
	spspedja NUMERIC(3, 0), 
	twspedja NUMERIC(3, 0), 
	miluntja VARCHAR(240), 
	trchrdja VARCHAR(6), 
	trchthja VARCHAR(5), 
	noprffja NUMERIC(2, 0), 
	netexwja NUMERIC(10, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ja PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb), 
	CONSTRAINT fk_ja_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE aa_ops_maint_requirements (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	serdesaa CHAR(1) NOT NULL, 
	maxttraa NUMERIC(5, 2), 
	percenaa NUMERIC(2, 0), 
	achavaaa NUMERIC(8, 6), 
	inhavaaa NUMERIC(8, 6), 
	omamdtaa NUMERIC(6, 1), 
	tmamdtaa NUMERIC(6, 1), 
	opmttraa NUMERIC(5, 2), 
	temttraa NUMERIC(5, 2), 
	nuoploaa NUMERIC(4, 0), 
	crewszaa NUMERIC(4, 0), 
	tosysuaa NUMERIC(6, 0), 
	rcmlogaa VARCHAR(32), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_aa PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa), 
	CONSTRAINT fk_aa_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE ak_system_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	seincdak CHAR(1) NOT NULL, 
	texseqak NUMERIC(5, 0) NOT NULL, 
	seinarak TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ak PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, seincdak, texseqak), 
	CONSTRAINT fk_ak_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE ag_reliability_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	measbsag CHAR(1) NOT NULL, 
	anopreag NUMERIC(6, 0), 
	oprqinag CHAR(1), 
	opmtbfag NUMERIC(10, 0), 
	temtbfag NUMERIC(10, 0), 
	opmrbmag NUMERIC(10, 0), 
	tmtbmaag NUMERIC(10, 0), 
	mtbrxxag NUMERIC(10, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ag PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, measbsag), 
	CONSTRAINT fk_ag_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE ah_interoperability_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	ionameah VARCHAR(19) NOT NULL, 
	iointyah CHAR(1) NOT NULL, 
	iocageah VARCHAR(5), 
	iorefnah VARCHAR(32), 
	ioniinah VARCHAR(9), 
	ionfscah VARCHAR(4), 
	ioitnmah VARCHAR(30), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ah PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, ionameah, iointyah), 
	CONSTRAINT fk_ah_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE aj_shipping_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	omlvlfnj CHAR(1) NOT NULL, 
	omlvltnj CHAR(1) NOT NULL, 
	shpdbnaj NUMERIC(4, 0), 
	timeshaj NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_aj PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, omlvlfnj, omlvltnj), 
	CONSTRAINT fk_aj_xb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE eh_alternate_nsn (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	serdnoef VARCHAR(10) NOT NULL, 
	srdrevef VARCHAR(2) NOT NULL, 
	altfsceh VARCHAR(4) NOT NULL, 
	altniieh VARCHAR(9) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_eh PRIMARY KEY (cagecdxh, refnumha, serdnoef, srdrevef, altfsceh, altniieh), 
	CONSTRAINT fk_eh_ef FOREIGN KEY(cagecdxh, refnumha, serdnoef, srdrevef) REFERENCES ef_serd_data (cagecdxh, refnumha, serdnoef, srdrevef) ON DELETE CASCADE
);

CREATE TABLE eg_serd_remarks (
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	serdnoef VARCHAR(10) NOT NULL, 
	srdrevef VARCHAR(2) NOT NULL, 
	texseqeg NUMERIC(5, 0) NOT NULL, 
	revremeg TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_eg PRIMARY KEY (cagecdxh, refnumha, serdnoef, srdrevef, texseqeg), 
	CONSTRAINT fk_eg_ef FOREIGN KEY(cagecdxh, refnumha, serdnoef, srdrevef) REFERENCES ef_serd_data (cagecdxh, refnumha, serdnoef, srdrevef) ON DELETE CASCADE
);

CREATE TABLE xe_lcn_serial_mapping (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxe VARCHAR(18) NOT NULL, 
	altlcnxe VARCHAR(2) NOT NULL, 
	lcntypxe CHAR(1) NOT NULL, 
	lcnseixe VARCHAR(18) NOT NULL, 
	alcseixe VARCHAR(2) NOT NULL, 
	ltyseixe CHAR(1) NOT NULL, 
	frsnumxe VARCHAR(10) NOT NULL, 
	tosnumxe VARCHAR(10) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_xe PRIMARY KEY (eiacodxa, lsaconxe, altlcnxe, lcntypxe, lcnseixe, alcseixe, ltyseixe, frsnumxe, tosnumxe), 
	CONSTRAINT fk_xe_item FOREIGN KEY(eiacodxa, lsaconxe, altlcnxe, lcntypxe) REFERENCES xb_lcn_indentured_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb), 
	CONSTRAINT fk_xe_serial FOREIGN KEY(eiacodxa, lcnseixe, alcseixe, ltyseixe, frsnumxe, tosnumxe) REFERENCES xd_system_serial_number (eiacodxa, lsaconxb, altlcnxb, lcntypxb, frsnumxd, tosnumxd)
);

CREATE TABLE cb_subtask_requirement (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	subnumcb VARCHAR(3) NOT NULL, 
	subtidcb VARCHAR(36), 
	rfdeiacb VARCHAR(10), 
	rfdlcncb VARCHAR(18), 
	fdalccb VARCHAR(2), 
	rfdtypcb CHAR(1), 
	rfdtcdcb VARCHAR(7), 
	rfdsubcb VARCHAR(3), 
	sbmmetcb NUMERIC(5, 1), 
	subwaccb VARCHAR(4), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_cb PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb), 
	CONSTRAINT fk_cb_ca FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) ON DELETE CASCADE
);

CREATE TABLE hh_overhaul_kit_nha (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	nhaplihh VARCHAR(5) NOT NULL, 
	nhaindhh CHAR(1), 
	ovhrephh NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hh PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, nhaplihh), 
	CONSTRAINT fk_hh_hg FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hi_provisioning_remark (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	texseqhi NUMERIC(5, 0) NOT NULL, 
	remarkhi TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hi PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, texseqhi), 
	CONSTRAINT fk_hi_hg FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hj_reference_designation (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	refdeshj VARCHAR(64) NOT NULL, 
	rdcodehj CHAR(1), 
	tmcodexi VARCHAR(3), 
	fignumhk VARCHAR(4), 
	itemnohk VARCHAR(4), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hj PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, refdeshj), 
	CONSTRAINT fk_hj_hg FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hk_parts_manual_desc (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	tmcodexi VARCHAR(3) NOT NULL, 
	fignumhk VARCHAR(4) NOT NULL, 
	itemnohk VARCHAR(4) NOT NULL, 
	tmfgcdhk VARCHAR(11), 
	tmindchk NUMERIC(1, 0), 
	qtyfighk NUMERIC(3, 0), 
	tmchgnhk NUMERIC(2, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hk PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, tmcodexi, fignumhk, itemnohk), 
	CONSTRAINT fk_hk_hg FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hn_prov_serial_uoc (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconhn VARCHAR(18) NOT NULL, 
	altlcnhn VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdhn VARCHAR(5) NOT NULL, 
	refnumhn VARCHAR(32) NOT NULL, 
	lcnseihn VARCHAR(18) NOT NULL, 
	alcseihn VARCHAR(2) NOT NULL, 
	frsnumhn VARCHAR(10) NOT NULL, 
	tosnumhn VARCHAR(10) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hn PRIMARY KEY (eiacodxa, lsaconhn, altlcnhn, lcntypxb, cagecdhn, refnumhn, lcnseihn, alcseihn, frsnumhn, tosnumhn), 
	CONSTRAINT fk_hn_hg FOREIGN KEY(eiacodxa, lsaconhn, altlcnhn, lcntypxb, cagecdhn, refnumhn) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE, 
	CONSTRAINT fk_hn_xd FOREIGN KEY(eiacodxa, lcnseihn, alcseihn, lcntypxb, frsnumhn, tosnumhn) REFERENCES xd_system_serial_number (eiacodxa, lsaconxb, altlcnxb, lcntypxb, frsnumxd, tosnumxd), 
	CONSTRAINT fk_hn_xd_validity FOREIGN KEY(eiacodxa, lcnseihn, alcseihn, lcntypxb, frsnumhn, tosnumhn) REFERENCES xd_system_serial_number (eiacodxa, lsaconxb, altlcnxb, lcntypxb, frsnumxd, tosnumxd)
);

CREATE TABLE ho_prov_system_uoc (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconho VARCHAR(18) NOT NULL, 
	altlcnho VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdho VARCHAR(5) NOT NULL, 
	refnumho VARCHAR(32) NOT NULL, 
	lcnseiho VARCHAR(18) NOT NULL, 
	alcseiho VARCHAR(2) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ho PRIMARY KEY (eiacodxa, lsaconho, altlcnho, lcntypxb, cagecdho, refnumho, lcnseiho, alcseiho), 
	CONSTRAINT fk_ho_hg FOREIGN KEY(eiacodxa, lsaconho, altlcnho, lcntypxb, cagecdho, refnumho) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE hp_design_change (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	canumbhp VARCHAR(15) NOT NULL, 
	rsplishp VARCHAR(5), 
	rspindhp CHAR(1), 
	intchchp VARCHAR(2), 
	totichhp NUMERIC(2, 0), 
	qtyshphp NUMERIC(6, 0), 
	qtyprohp NUMERIC(6, 0), 
	proelihp VARCHAR(6), 
	proqtyhp NUMERIC(6, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hp PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, canumbhp), 
	CONSTRAINT fk_hp_hg FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha) ON DELETE CASCADE
);

CREATE TABLE cf_task_remark_ref (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	tskrrcce VARCHAR(2) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_cf PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, tskrrcce), 
	CONSTRAINT fk_cf_ca FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) ON DELETE CASCADE, 
	CONSTRAINT fk_cf_ce FOREIGN KEY(eiacodxa, tskrrcce) REFERENCES ce_task_remark (eiacodxa, tskrrcce)
);

CREATE TABLE cg_task_support_equipment (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	tscagecg VARCHAR(5) NOT NULL, 
	tsrefncg VARCHAR(32) NOT NULL, 
	sqtytkcg NUMERIC(5, 2), 
	sqtkumcg VARCHAR(2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_cg PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, tscagecg, tsrefncg), 
	CONSTRAINT fk_cg_ca FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) ON DELETE CASCADE, 
	CONSTRAINT fk_cg_ea_tool_validity FOREIGN KEY(tscagecg, tsrefncg) REFERENCES ea_support_equipment (cagecdxh, refnumha)
);

CREATE TABLE ch_task_manual (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	tmcodexi VARCHAR(3) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ch PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, tmcodexi), 
	CONSTRAINT fk_ch_ca FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) ON DELETE CASCADE, 
	CONSTRAINT fk_ch_xi FOREIGN KEY(tmcodexi) REFERENCES xi_tech_manual_index (tmcodexi)
);

CREATE TABLE ub_uut_support_equipment (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	secageea VARCHAR(5) NOT NULL, 
	serefnea VARCHAR(32) NOT NULL, 
	utstcdub CHAR(1), 
	utcmrsub CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ub PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea), 
	CONSTRAINT fk_ub_ea FOREIGN KEY(secageea, serefnea) REFERENCES ea_support_equipment (cagecdxh, refnumha), 
	CONSTRAINT fk_ub_ea_tester_validity FOREIGN KEY(secageea, serefnea) REFERENCES ea_support_equipment (cagecdxh, refnumha), 
	CONSTRAINT fk_ub_ua FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua) REFERENCES ua_unit_under_test (eiacodxa, uutlcnua, uutalcua, utlcntua) ON DELETE CASCADE
);

CREATE TABLE uf_uut_explanation (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	texsequf NUMERIC(5, 0) NOT NULL, 
	utexpluf TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_uf PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua, texsequf), 
	CONSTRAINT fk_uf_ua FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua) REFERENCES ua_unit_under_test (eiacodxa, uutlcnua, uutalcua, utlcntua) ON DELETE CASCADE
);

CREATE TABLE un_se_uut_parameter_group (
	tgscagun VARCHAR(5) NOT NULL, 
	tgsrefun VARCHAR(32) NOT NULL, 
	sutcagum VARCHAR(5) NOT NULL, 
	sutrefum VARCHAR(32) NOT NULL, 
	seupgcun VARCHAR(2) NOT NULL, 
	utpacmun CHAR(1), 
	utpaacun VARCHAR(26), 
	utpaioun CHAR(1), 
	utpapaun VARCHAR(12), 
	utrgfrun NUMERIC(10, 0), 
	utprrtun NUMERIC(10, 0), 
	utparvun CHAR(1), 
	utpataun CHAR(1), 
	utpatdun CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_un PRIMARY KEY (tgscagun, tgsrefun, sutcagum, sutrefum, seupgcun), 
	CONSTRAINT fk_un_ea FOREIGN KEY(tgscagun, tgsrefun) REFERENCES ea_support_equipment (cagecdxh, refnumha), 
	CONSTRAINT fk_un_um FOREIGN KEY(sutcagum, sutrefum) REFERENCES um_se_item_uut (sutcagum, sutrefum)
);

CREATE TABLE bd_ram_indicators (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	ramindbd CHAR(1) NOT NULL, 
	achavabd NUMERIC(8, 6), 
	inhavabd NUMERIC(8, 6), 
	failrtbd NUMERIC(10, 0), 
	farambbd CHAR(1), 
	inhmafbd NUMERIC(2, 1), 
	maxttrbd NUMERIC(5, 2), 
	percenbd NUMERIC(2, 0), 
	mttropbd NUMERIC(5, 2), 
	mttrthbd NUMERIC(5, 2), 
	opmtbfbd NUMERIC(10, 0), 
	omtbfmbd CHAR(1), 
	temtbfbd NUMERIC(10, 0), 
	tmtbfmbd CHAR(1), 
	omtbmaab NUMERIC(10, 0), 
	omtbmmbd CHAR(1), 
	tmtbmabd NUMERIC(10, 0), 
	tmtbmmbd CHAR(1), 
	inmtbmbd NUMERIC(10, 0), 
	imtbmmbd CHAR(1), 
	inhmtbbd NUMERIC(10, 0), 
	inhmtmbd CHAR(1), 
	nomtbmbd NUMERIC(10, 0), 
	nmtbmmbd CHAR(1), 
	mtbmpvbd NUMERIC(10, 0), 
	mtbmpmbd CHAR(1), 
	mtbrxxbd NUMERIC(10, 0), 
	mtbrmbbd CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bd PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, ramindbd), 
	CONSTRAINT fk_bd_ba FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ba_ram_characteristics (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE bb_ram_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	ramcnabb CHAR(1) NOT NULL, 
	texseqbb NUMERIC(5, 0) NOT NULL, 
	ramnarbb TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bb PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, ramcnabb, texseqbb), 
	CONSTRAINT fk_bb_ba FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ba_ram_characteristics (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE bc_logistics_considerations (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	lococobc CHAR(1) NOT NULL, 
	texseqbc NUMERIC(5, 0) NOT NULL, 
	lognarbc TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bc PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, lococobc, texseqbc), 
	CONSTRAINT fk_bc_ba FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ba_ram_characteristics (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE bf_failure_mode_analysis (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	famoinbf VARCHAR(4) NOT NULL, 
	efmtbfbf NUMERIC(10, 0), 
	efmmmbbf CHAR(1), 
	fmclasbf CHAR(1), 
	fmratobf NUMERIC(4, 3), 
	rcmro1bf CHAR(1), 
	rcmro2bf CHAR(1), 
	rcmro3bf CHAR(1), 
	rcmro4bf CHAR(1), 
	rcmro5bf CHAR(1), 
	rcmro6bf CHAR(1), 
	rcmro7bf CHAR(1), 
	rcmro8bf CHAR(1), 
	rcmro9bf CHAR(1), 
	rcmr10bf CHAR(1), 
	rcmr11bf CHAR(1), 
	rcmr12bf CHAR(1), 
	rcmr13bf CHAR(1), 
	rcmr14bf CHAR(1), 
	rcmr15bf CHAR(1), 
	rcmr16bf CHAR(1), 
	rcmr17bf CHAR(1), 
	rcmr18bf CHAR(1), 
	rcmr19bf CHAR(1), 
	rcmr20bf CHAR(1), 
	rcmr21bf CHAR(1), 
	rcmr22bf CHAR(1), 
	rcmr23bf CHAR(1), 
	rcmr24bf CHAR(1), 
	rcmr25bf CHAR(1), 
	rcmdsabf CHAR(1), 
	rcmdsbbf CHAR(1), 
	rcmdscbf CHAR(1), 
	rcmdsdbf CHAR(1), 
	rcmdsebf CHAR(1), 
	rcmdsfbf CHAR(1), 
	rcmdsgbf CHAR(1), 
	rcmdshbf CHAR(1), 
	rcmdsibf CHAR(1), 
	rcmdsjbf CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bf PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf), 
	CONSTRAINT fk_bf_ba FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ba_ram_characteristics (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE fe_task_facility_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	facnamfa VARCHAR(32) NOT NULL, 
	facccdfa VARCHAR(6) NOT NULL, 
	factypfa CHAR(1) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_fe PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, facnamfa, facccdfa, factypfa), 
	CONSTRAINT fk_fe_ca FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) ON DELETE CASCADE, 
	CONSTRAINT fk_fe_fa FOREIGN KEY(facnamfa, facccdfa, factypfa) REFERENCES fa_facility (facnamfa, facccdfa, factypfa)
);

CREATE TABLE jb_shipping_mode (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	tmncnjb NUMERIC(2, 0) NOT NULL, 
	trchmtjb CHAR(1) NOT NULL, 
	tritdrjb VARCHAR(26), 
	shpconjb VARCHAR(2), 
	conlenjb NUMERIC(2, 0), 
	contypjb VARCHAR(36), 
	frclasjb VARCHAR(7), 
	eoilinjb CHAR(1), 
	hmatlrjb NUMERIC(5, 0), 
	hmdisrjb NUMERIC(3, 0), 
	hmpayrjb NUMERIC(5, 0), 
	hmtmprjb NUMERIC(3, 0), 
	hmtimrjb NUMERIC(3, 1), 
	hiprmljb CHAR(1), 
	hiprmtjb VARCHAR(19), 
	haltmljb CHAR(1), 
	haltmtjb VARCHAR(19), 
	railusjb VARCHAR(5), 
	railtcjb VARCHAR(240), 
	sdecksjb CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_jb PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, tmncnjb, trchmtjb), 
	CONSTRAINT fk_jb_ja FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ja_transportation (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE jc_transported_end_item (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	trconmjc NUMERIC(2, 0) NOT NULL, 
	mobtypjc CHAR(1) NOT NULL, 
	opweemjc NUMERIC(4, 1), 
	hiclnejc NUMERIC(2, 0), 
	opweldjc NUMERIC(4, 1), 
	hiclnljc NUMERIC(2, 0), 
	shweemjc NUMERIC(4, 1), 
	shweldjc NUMERIC(4, 1), 
	creangjc NUMERIC(2, 0), 
	trgrprjc NUMERIC(7, 0), 
	trrwwtjc NUMERIC(6, 0), 
	trnuptjc NUMERIC(2, 0), 
	trpsarjc NUMERIC(6, 1), 
	tpsaumjc VARCHAR(2), 
	whinprjc NUMERIC(3, 0), 
	whnupljc NUMERIC(2, 0), 
	whnutijc NUMERIC(2, 0), 
	whtldrjc VARCHAR(10), 
	whtiftjc VARCHAR(10), 
	whwemjc VARCHAR(10), 
	twalfijc NUMERIC(4, 1), 
	twalfojc NUMERIC(4, 1), 
	twalrijc NUMERIC(4, 1), 
	twalrojc NUMERIC(4, 1), 
	snumskjc NUMERIC(2, 0), 
	sdsicgjc NUMERIC(6, 1), 
	skadumjc VARCHAR(2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_jc PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, trconmjc, mobtypjc), 
	CONSTRAINT fk_jc_ja FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ja_transportation (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE je_transport_fiscal_year (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	trafyrje VARCHAR(2) NOT NULL, 
	fiqpqtje NUMERIC(3, 0), 
	sqpqtyje NUMERIC(3, 0), 
	tqpqtyje NUMERIC(3, 0), 
	fqpqtyje NUMERIC(3, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_je PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, trafyrje), 
	CONSTRAINT fk_je_ja FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ja_transportation (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE jf_transportation_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	trancdjf CHAR(1) NOT NULL, 
	texseqjf NUMERIC(5, 0) NOT NULL, 
	trnarjf TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_jf PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, trancdjf, texseqjf), 
	CONSTRAINT fk_jf_ja FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb) REFERENCES ja_transportation (eiacodxa, lsaconxb, altlcnxb, lcntypxb) ON DELETE CASCADE
);

CREATE TABLE ab_war_peace_requirements (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	serdesaa CHAR(1) NOT NULL, 
	oprqinab CHAR(1) NOT NULL, 
	annomiab NUMERIC(6, 0), 
	anopdaab NUMERIC(3, 0), 
	anoptiab NUMERIC(4, 0), 
	mmisduab NUMERIC(6, 1), 
	mmisdmab CHAR(1), 
	opavaiab NUMERIC(8, 6), 
	opaldtab NUMERIC(3, 0), 
	ostbtiab NUMERIC(4, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ab PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab), 
	CONSTRAINT fk_ab_aa FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa) REFERENCES aa_ops_maint_requirements (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa) ON DELETE CASCADE
);

CREATE TABLE ci_task_provisioned_item (
	eiacodxa VARCHAR(10) NOT NULL, 
	tsklcnci VARCHAR(18) NOT NULL, 
	tskalcci VARCHAR(2) NOT NULL, 
	tskltyci CHAR(1) NOT NULL, 
	tsktcdci VARCHAR(7) NOT NULL, 
	procagci VARCHAR(5) NOT NULL, 
	prorefci VARCHAR(32) NOT NULL, 
	prolcnci VARCHAR(18) NOT NULL, 
	proalcci VARCHAR(2) NOT NULL, 
	proltyci CHAR(1) NOT NULL, 
	pqtytkci NUMERIC(5, 2), 
	pqtkumci VARCHAR(2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ci PRIMARY KEY (eiacodxa, tsklcnci, tskalcci, tskltyci, tsktcdci, procagci, prorefci, prolcnci, proalcci, proltyci), 
	CONSTRAINT fk_ci_ca FOREIGN KEY(eiacodxa, tsklcnci, tskalcci, tskltyci, tsktcdci) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca) ON DELETE CASCADE, 
	CONSTRAINT fk_ci_hg_bom_validity FOREIGN KEY(eiacodxa, prolcnci, proalcci, proltyci, procagci, prorefci) REFERENCES hg_part_application (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha)
);

CREATE TABLE hl_parts_manual_nomen (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	tmcodexi VARCHAR(3) NOT NULL, 
	fignumhk VARCHAR(4) NOT NULL, 
	itemnohk VARCHAR(4) NOT NULL, 
	texseqhl NUMERIC(5, 0) NOT NULL, 
	provnohl TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hl PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, tmcodexi, fignumhk, itemnohk, texseqhl), 
	CONSTRAINT fk_hl_hk FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, tmcodexi, fignumhk, itemnohk) REFERENCES hk_parts_manual_desc (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, tmcodexi, fignumhk, itemnohk) ON DELETE CASCADE
);

CREATE TABLE hq_serial_num_effectivity (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdxh VARCHAR(5) NOT NULL, 
	refnumha VARCHAR(32) NOT NULL, 
	canumbhp VARCHAR(15) NOT NULL, 
	fmsrnohq VARCHAR(10) NOT NULL, 
	tosrnohq VARCHAR(10) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hq PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, canumbhp, fmsrnohq, tosrnohq), 
	CONSTRAINT fk_hq_hp FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, canumbhp) REFERENCES hp_design_change (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, canumbhp) ON DELETE CASCADE
);

CREATE TABLE hr_design_change_uoc (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconho VARCHAR(18) NOT NULL, 
	altlcnho VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	cagecdho VARCHAR(5) NOT NULL, 
	refnumho VARCHAR(32) NOT NULL, 
	canumbhp VARCHAR(15) NOT NULL, 
	lcnseiho VARCHAR(18) NOT NULL, 
	alcseiho VARCHAR(2) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_hr PRIMARY KEY (eiacodxa, lsaconho, altlcnho, lcntypxb, cagecdho, refnumho, canumbhp, lcnseiho, alcseiho), 
	CONSTRAINT fk_hr_ho FOREIGN KEY(eiacodxa, lsaconho, altlcnho, lcntypxb, cagecdho, refnumho, lcnseiho, alcseiho) REFERENCES ho_prov_system_uoc (eiacodxa, lsaconho, altlcnho, lcntypxb, cagecdho, refnumho, lcnseiho, alcseiho), 
	CONSTRAINT fk_hr_hp FOREIGN KEY(eiacodxa, lsaconho, altlcnho, lcntypxb, cagecdho, refnumho, canumbhp) REFERENCES hp_design_change (eiacodxa, lsaconxb, altlcnxb, lcntypxb, cagecdxh, refnumha, canumbhp) ON DELETE CASCADE
);

CREATE TABLE cc_sequential_subtask_description (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	subnumcb VARCHAR(3) NOT NULL, 
	texseqcc NUMERIC(5, 0) NOT NULL, 
	subnarcc TEXT, 
	elemntcc CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_cc PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, texseqcc), 
	CONSTRAINT fk_cc_cb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb) REFERENCES cb_subtask_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb) ON DELETE CASCADE
);

CREATE TABLE cd_subtask_personnel_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	subnumcb VARCHAR(3) NOT NULL, 
	subpidcd VARCHAR(3) NOT NULL, 
	skspcdga VARCHAR(7), 
	mdcsscgb VARCHAR(7), 
	submmmcd NUMERIC(4, 1), 
	ssecdecd CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_cd PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd), 
	CONSTRAINT fk_cd_cb FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb) REFERENCES cb_subtask_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb) ON DELETE CASCADE
);

CREATE TABLE ud_uut_se_otp (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	secageea VARCHAR(5) NOT NULL, 
	serefnea VARCHAR(32) NOT NULL, 
	otpcaguc VARCHAR(5) NOT NULL, 
	otprefuc VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ud PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea, otpcaguc, otprefuc), 
	CONSTRAINT fk_ud_ub FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) REFERENCES ub_uut_support_equipment (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) ON DELETE CASCADE, 
	CONSTRAINT fk_ud_uc FOREIGN KEY(otpcaguc, otprefuc) REFERENCES uc_operational_test_program (otpcaguc, otprefuc)
);

CREATE TABLE ug_uut_parameter_group (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	secageea VARCHAR(5) NOT NULL, 
	serefnea VARCHAR(32) NOT NULL, 
	wtpgcug VARCHAR(2) NOT NULL, 
	wtppcug CHAR(1), 
	wtpacug VARCHAR(26), 
	wtpioug CHAR(1), 
	uutpsoug CHAR(1), 
	uutparug VARCHAR(12), 
	uutprtug NUMERIC(10, 0), 
	uutprfug NUMERIC(10, 0), 
	uutprvug CHAR(1), 
	uutptaug CHAR(1), 
	uutptdug CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ug PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea, wtpgcug), 
	CONSTRAINT fk_ug_ub FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) REFERENCES ub_uut_support_equipment (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) ON DELETE CASCADE
);

CREATE TABLE uj_uut_se_aid (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	secageea VARCHAR(5) NOT NULL, 
	serefnea VARCHAR(32) NOT NULL, 
	aidcagui VARCHAR(5) NOT NULL, 
	aidrefui VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_uj PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea, aidcagui, aidrefui), 
	CONSTRAINT fk_uj_ub FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) REFERENCES ub_uut_support_equipment (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) ON DELETE CASCADE, 
	CONSTRAINT fk_uj_ui FOREIGN KEY(aidcagui, aidrefui) REFERENCES ui_adapter_interconnector (aidcagui, aidrefui)
);

CREATE TABLE ul_uut_se_ate (
	eiacodxa VARCHAR(10) NOT NULL, 
	uutlcnua VARCHAR(18) NOT NULL, 
	uutalcua VARCHAR(2) NOT NULL, 
	utlcntua CHAR(1) NOT NULL, 
	secageea VARCHAR(5) NOT NULL, 
	serefnea VARCHAR(32) NOT NULL, 
	atecaguk VARCHAR(5) NOT NULL, 
	aterefuk VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ul PRIMARY KEY (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea, atecaguk, aterefuk), 
	CONSTRAINT fk_ul_ub FOREIGN KEY(eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) REFERENCES ub_uut_support_equipment (eiacodxa, uutlcnua, uutalcua, utlcntua, secageea, serefnea) ON DELETE CASCADE, 
	CONSTRAINT fk_ul_uk FOREIGN KEY(atecaguk, aterefuk) REFERENCES uk_ate_test_station (atecaguk, aterefuk)
);

CREATE TABLE be_war_peace_ram (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	ramindbd CHAR(1) NOT NULL, 
	oprqinbe CHAR(1) NOT NULL, 
	aldtxxbe NUMERIC(3, 0), 
	opavaibe NUMERIC(8, 6), 
	stabytbe NUMERIC(4, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_be PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, ramindbd, oprqinbe), 
	CONSTRAINT fk_be_bd FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, ramindbd) REFERENCES bd_ram_indicators (eiacodxa, lsaconxb, altlcnxb, lcntypxb, ramindbd) ON DELETE CASCADE
);

CREATE TABLE bg_failure_mode_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	famoinbf VARCHAR(4) NOT NULL, 
	fmncnabg CHAR(1) NOT NULL, 
	texseqbg NUMERIC(5, 0) NOT NULL, 
	fmnnarbg TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bg PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf, fmncnabg, texseqbg), 
	CONSTRAINT fk_bg_bf FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf) REFERENCES bf_failure_mode_analysis (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf) ON DELETE CASCADE
);

CREATE TABLE bh_failure_mode_task (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconbh VARCHAR(18) NOT NULL, 
	altlcnbh VARCHAR(2) NOT NULL, 
	lcntypbh CHAR(1) NOT NULL, 
	famoinbh VARCHAR(4) NOT NULL, 
	tslsacnbh VARCHAR(18) NOT NULL, 
	talcncbh VARCHAR(2) NOT NULL, 
	tlcntybh CHAR(1) NOT NULL, 
	ttaskcbh VARCHAR(7) NOT NULL, 
	tatypebh CHAR(1), 
	maininbh NUMERIC(10, 0), 
	mainmbbh CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bh PRIMARY KEY (eiacodxa, lsaconbh, altlcnbh, lcntypbh, famoinbh, tslsacnbh, talcncbh, tlcntybh, ttaskcbh), 
	CONSTRAINT fk_bh_bf FOREIGN KEY(eiacodxa, lsaconbh, altlcnbh, lcntypbh, famoinbh) REFERENCES bf_failure_mode_analysis (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf), 
	CONSTRAINT fk_bh_ca FOREIGN KEY(eiacodxa, tslsacnbh, talcncbh, tlcntybh, ttaskcbh) REFERENCES ca_task_requirement (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca)
);

CREATE TABLE bi_failure_mode_mission_data (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	famoinbf VARCHAR(4) NOT NULL, 
	misspcbl VARCHAR(1) NOT NULL, 
	fmshscbi CHAR(1) NOT NULL, 
	feprobbi NUMERIC(3, 2), 
	facrnubi NUMERIC(10, 0), 
	fproblbi CHAR(1), 
	fmoptibi NUMERIC(6, 2), 
	fmotmbbi CHAR(1), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bi PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf, misspcbl), 
	CONSTRAINT fk_bi_bf FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf) REFERENCES bf_failure_mode_analysis (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf) ON DELETE CASCADE, 
	CONSTRAINT fk_bi_bl FOREIGN KEY(eiacodxa, misspcbl) REFERENCES bl_mission_phase_mode (eiacodxa, misspcbl)
);

CREATE TABLE jd_transported_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	trconmjc NUMERIC(2, 0) NOT NULL, 
	mobtypjc CHAR(1) NOT NULL, 
	treincjd CHAR(1) NOT NULL, 
	texseqjd NUMERIC(5, 0) NOT NULL, 
	whtrlojd TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_jd PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, trconmjc, mobtypjc, treincjd, texseqjd), 
	CONSTRAINT fk_jd_jc FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, trconmjc, mobtypjc) REFERENCES jc_transported_end_item (eiacodxa, lsaconxb, altlcnxb, lcntypxb, trconmjc, mobtypjc) ON DELETE CASCADE
);

CREATE TABLE ac_maintenance_level_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	serdesaa CHAR(1) NOT NULL, 
	oprqinab CHAR(1) NOT NULL, 
	omlvlcac CHAR(1) NOT NULL, 
	mlmttrac NUMERIC(5, 2), 
	mlpercac NUMERIC(2, 0), 
	mlnssuac NUMERIC(6, 0), 
	mlsamhac NUMERIC(6, 1), 
	mluamhac NUMERIC(6, 1), 
	mlsmhoac NUMERIC(8, 5), 
	mlumhoac NUMERIC(8, 5), 
	mlumetac NUMERIC(5, 2), 
	mlummhac NUMERIC(5, 2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ac PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab, omlvlcac), 
	CONSTRAINT fk_ac_ab FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab) REFERENCES ab_war_peace_requirements (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab) ON DELETE CASCADE
);

CREATE TABLE ad_organizational_level_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	serdesaa CHAR(1) NOT NULL, 
	oprqinab CHAR(1) NOT NULL, 
	omlvlcac CHAR(1) NOT NULL, 
	dinmetad NUMERIC(5, 2), 
	dinmmhad NUMERIC(5, 2), 
	premetad NUMERIC(5, 2), 
	premmhad NUMERIC(5, 2), 
	poimetad NUMERIC(5, 2), 
	poimmhad NUMERIC(5, 2), 
	pinmetad NUMERIC(5, 2), 
	pinmmhad NUMERIC(5, 2), 
	mpcmetad NUMERIC(5, 2), 
	mpcmmhad NUMERIC(5, 2), 
	tinmetad NUMERIC(5, 2), 
	tinmmhad NUMERIC(5, 2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ad PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab, omlvlcac), 
	CONSTRAINT fk_ad_ab FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab) REFERENCES ab_war_peace_requirements (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab) ON DELETE CASCADE
);

CREATE TABLE af_war_peace_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	serdesaa CHAR(1) NOT NULL, 
	oprqinab CHAR(1) NOT NULL, 
	texseqaf NUMERIC(5, 0) NOT NULL, 
	wpaddraf TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_af PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab, texseqaf), 
	CONSTRAINT fk_af_ab FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab) REFERENCES ab_war_peace_requirements (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab) ON DELETE CASCADE
);

CREATE TABLE ck_task_inventory (
	jobcodcj VARCHAR(2) NOT NULL, 
	dutycdcj VARCHAR(4) NOT NULL, 
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	subnumcb VARCHAR(3) NOT NULL, 
	subpidcd VARCHAR(3) NOT NULL, 
	tsfromck NUMERIC(5, 0), 
	texttock NUMERIC(5, 0), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ck PRIMARY KEY (jobcodcj, dutycdcj, eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd), 
	CONSTRAINT fk_ck_cd FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd) REFERENCES cd_subtask_personnel_req (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd) ON DELETE CASCADE, 
	CONSTRAINT fk_ck_cj FOREIGN KEY(jobcodcj, dutycdcj) REFERENCES cj_job_duty_assignment (jobcodcj, dutycdcj)
);

CREATE TABLE bj_failure_mode_mission_narrative (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	famoinbf VARCHAR(4) NOT NULL, 
	misspcbl VARCHAR(1) NOT NULL, 
	fmmpcnbj CHAR(1) NOT NULL, 
	texseqbj NUMERIC(5, 0) NOT NULL, 
	fmcnarbj TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_bj PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf, misspcbl, fmmpcnbj, texseqbj), 
	CONSTRAINT fk_bj_bi FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf, misspcbl) REFERENCES bi_failure_mode_mission_data (eiacodxa, lsaconxb, altlcnxb, lcntypxb, famoinbf, misspcbl) ON DELETE CASCADE
);

CREATE TABLE ge_physical_mental_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	taskcdca VARCHAR(7) NOT NULL, 
	subnumcb VARCHAR(3) NOT NULL, 
	subpidcd VARCHAR(3) NOT NULL, 
	mdcsscgb VARCHAR(7) NOT NULL, 
	texseqge NUMERIC(5, 0) NOT NULL, 
	pamenrge TEXT, 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ge PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd, mdcsscgb, texseqge), 
	CONSTRAINT fk_ge_cd FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd) REFERENCES cd_subtask_personnel_req (eiacodxa, lsaconxb, altlcnxb, lcntypxb, taskcdca, subnumcb, subpidcd) ON DELETE CASCADE, 
	CONSTRAINT fk_ge_gb FOREIGN KEY(mdcsscgb) REFERENCES gb_new_modified_skill (mdcsscgb)
);

CREATE TABLE ae_skill_ops_maint_req (
	eiacodxa VARCHAR(10) NOT NULL, 
	lsaconxb VARCHAR(18) NOT NULL, 
	altlcnxb VARCHAR(2) NOT NULL, 
	lcntypxb CHAR(1) NOT NULL, 
	serdesaa CHAR(1) NOT NULL, 
	oprqinab CHAR(1) NOT NULL, 
	omlvlcac CHAR(1) NOT NULL, 
	skspcdga VARCHAR(7) NOT NULL, 
	avaimhae NUMERIC(6, 0), 
	qtyavaae NUMERIC(5, 0), 
	utratiae NUMERIC(3, 2), 
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	last_modified_by VARCHAR(50), 
	CONSTRAINT pk_ae PRIMARY KEY (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab, omlvlcac, skspcdga), 
	CONSTRAINT fk_ae_ac FOREIGN KEY(eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab, omlvlcac) REFERENCES ac_maintenance_level_req (eiacodxa, lsaconxb, altlcnxb, lcntypxb, serdesaa, oprqinab, omlvlcac) ON DELETE CASCADE
);

